# Generated by Django 5.0.7 on 2024-07-29 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId1', models.BigIntegerField()),
                ('userId2', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('reciever', models.CharField(max_length=100)),
                ('dmId', models.BigIntegerField()),
                ('message', models.CharField(max_length=550)),
                ('readStatus', models.BooleanField()),
                ('sendStatus', models.BooleanField()),
                ('replyStatus', models.BooleanField()),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('deletedAt', models.DateTimeField()),
            ],
        ),
    ]
