# Generated by Django 5.0.7 on 2024-07-29 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reciever',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='userId1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='userId2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='readStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='replyStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='sendStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
