# Generated by Django 5.0.7 on 2024-07-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_message_reciever_message_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='message',
            name='dmId',
        ),
        migrations.RemoveField(
            model_name='message',
            name='readStatus',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replyStatus',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sendStatus',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
