# Generated by Django 5.0.7 on 2024-07-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message_replystatus_contacts_delete_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='Başlık', max_length=50),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
