# Generated by Django 5.0.7 on 2024-07-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_message_title_delete_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messagefirst14',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='Yanıt Başlığı', max_length=50),
        ),
    ]
