# Generated by Django 5.0.7 on 2024-08-01 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_message_messagefirst14'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='message',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
