# Generated by Django 5.0.7 on 2024-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readStatus',
            field=models.BooleanField(default=False),
        ),
    ]
